In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max.columns', None)

In [2]:
# suppress warnings
import warnings
warnings.filterwarnings('ignore')

In [5]:
data = pd.read_csv('Home_Loan/application_train.csv.tar.gz')

In [6]:
train_data = data.copy()
train_data.head()

application_train.csv  TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR  \
0               100002.0     1.0         Cash loans           M            N   
1               100003.0     0.0         Cash loans           F            N   
2               100004.0     0.0    Revolving loans           M            Y   
3               100006.0     0.0         Cash loans           F            N   
4               100007.0     0.0         Cash loans           M            N   

  FLAG_OWN_REALTY  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
0               Y           0.0          202500.0    406597.5      24700.5   
1               N           0.0          270000.0   1293502.5      35698.5   
2               Y           0.0           67500.0    135000.0       6750.0   
3               Y           0.0          135000.0    312682.5      29686.5   
4               Y           0.0          121500.0    513000.0      21865.5   

   AMT_GOODS_PRICE NAME_TYPE_SUITE NAME_INCOME_TYPE  \
0         351000.0   Unaccompanied          Working   
1        1129500.0          Family    State servant   
2         135000.0   Unaccompanied          Working   
3         297000.0   Unaccompanied          Working   
4         513000.0   Unaccompanied          Working   

             NAME_EDUCATION_TYPE    NAME_FAMILY_STATUS  NAME_HOUSING_TYPE  \
0  Secondary / secondary special  Single / not married  House / apartment   
1               Higher education               Married  House / apartment   
2  Secondary / secondary special  Single / not married  House / apartment   
3  Secondary / secondary special        Civil marriage  House / apartment   
4  Secondary / secondary special  Single / not married  House / apartment   

   REGION_POPULATION_RELATIVE  DAYS_BIRTH  DAYS_EMPLOYED  DAYS_REGISTRATION  \
0                    0.018801     -9461.0         -637.0            -3648.0   
1                    0.003541    -16765.0        -1188.0            -1186.0   
2                    0.010032    -19046.0         -225.0            -4260.0   
3                    0.008019    -19005.0        -3039.0            -9833.0   
4                    0.028663    -19932.0        -3038.0            -4311.0   

   DAYS_ID_PUBLISH  OWN_CAR_AGE  FLAG_MOBIL  FLAG_EMP_PHONE  FLAG_WORK_PHONE  \
0          -2120.0          NaN         1.0             1.0              0.0   
1           -291.0          NaN         1.0             1.0              0.0   
2          -2531.0         26.0         1.0             1.0              1.0   
3          -2437.0          NaN         1.0             1.0              0.0   
4          -3458.0          NaN         1.0             1.0              0.0   

   FLAG_CONT_MOBILE  FLAG_PHONE  FLAG_EMAIL OCCUPATION_TYPE  CNT_FAM_MEMBERS  \
0               1.0         1.0         0.0        Laborers              1.0   
1               1.0         1.0         0.0      Core staff              2.0   
2               1.0         1.0         0.0        Laborers              1.0   
3               1.0         0.0         0.0        Laborers              2.0   
4               1.0         0.0         0.0      Core staff              1.0   

   REGION_RATING_CLIENT  REGION_RATING_CLIENT_W_CITY  \
0                   2.0                          2.0   
1                   1.0                          1.0   
2                   2.0                          2.0   
3                   2.0                          2.0   
4                   2.0                          2.0   

  WEEKDAY_APPR_PROCESS_START  HOUR_APPR_PROCESS_START  \
0                  WEDNESDAY                     10.0   
1                     MONDAY                     11.0   
2                     MONDAY                      9.0   
3                  WEDNESDAY                     17.0   
4                   THURSDAY                     11.0   

   REG_REGION_NOT_LIVE_REGION  REG_REGION_NOT_WORK_REGION  \
0                         0.0                         0.0   
1                   

In [7]:
train_data['TARGET'].value_counts()

0.0    282686
1.0     24825
Name: TARGET, dtype: int64

In [8]:
# Function to calculate missing values in each column
def missing_values(df):
    # Total missing values
    mis_values = df.isnull().sum()
    # percentage of total missing values
    mis_values_percent = (100 * mis_values) / len(df)
    # table with missing values
    mis_values_table = pd.concat([mis_values, mis_values_percent], axis=1)
    
    # rename the columns
    mis_values_table = mis_values_table.rename(columns={0 : 'Missing Values', 1 : '% of Missing Values'})
    
    # sorting the table per percentage
    mis_values_table = mis_values_table[mis_values_table.iloc[:,1] != 0].sort_values(
        '% of Missing Values', ascending = False).round(2)
    
    return mis_values_table

In [9]:
missing_values_table = missing_values(train_data)

In [10]:
missing_values_table.head(20)

Missing Values  % of Missing Values
COMMONAREA_MEDI                   214866                69.87
COMMONAREA_AVG                    214866                69.87
COMMONAREA_MODE                   214866                69.87
NONLIVINGAPARTMENTS_MODE          213515                69.43
NONLIVINGAPARTMENTS_AVG           213515                69.43
NONLIVINGAPARTMENTS_MEDI          213515                69.43
FONDKAPREMONT_MODE                210296                68.39
LIVINGAPARTMENTS_MODE             210200                68.36
LIVINGAPARTMENTS_AVG              210200                68.36
LIVINGAPARTMENTS_MEDI             210200                68.36
FLOORSMIN_AVG                     208643                67.85
FLOORSMIN_MODE                    208643                67.85
FLOORSMIN_MEDI                    208643                67.85
YEARS_BUILD_MEDI                  204489                66.50
YEARS_BUILD_MODE                  204489                66.50
YEARS_BUILD_AVG                   204489                66.50
OWN_CAR_AGE                       202930                65.99
LANDAREA_MEDI                     182591                59.38
LANDAREA_MODE                     182591                59.38
LANDAREA_AVG                      182591                59.38

In [11]:
train_data.shape

(307512, 122)

In [12]:
train_data_clean = train_data.dropna()

In [13]:
train_data_clean.shape

(8602, 122)

In [14]:
missing_values(train_data_clean)

Empty DataFrame
Columns: [Missing Values, % of Missing Values]
Index: []

In [15]:
model_data = train_data_clean[['TARGET', 'NAME_CONTRACT_TYPE','CODE_GENDER', 'FLAG_OWN_CAR','FLAG_OWN_REALTY',
                             'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY', 'AMT_GOODS_PRICE',
                             'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'DAYS_BIRTH',
                             'DAYS_EMPLOYED', 'REGION_RATING_CLIENT_W_CITY', 'EXT_SOURCE_2', 'FLAG_DOCUMENT_2', 'FLAG_DOCUMENT_21']]

In [16]:
model_data.head()

TARGET NAME_CONTRACT_TYPE CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  \
71      0.0         Cash loans           M            Y               Y   
124     0.0         Cash loans           F            Y               Y   
152     0.0         Cash loans           F            Y               N   
161     0.0         Cash loans           M            Y               N   
255     1.0         Cash loans           M            Y               N   

     CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  AMT_GOODS_PRICE  \
71            0.0          103500.0    573628.5      24435.0         463500.0   
124           1.0          202500.0    260725.5      16789.5         198000.0   
152           0.0          202500.0    675000.0      53329.5         675000.0   
161           0.0          162000.0    263686.5      24781.5         238500.0   
255           1.0          225000.0   1019205.0      31032.0         774000.0   

         NAME_INCOME_TYPE            NAME_EDUCATION_TYPE  \
71                Working  Secondary / secondary special   
124               Working  Secondary / secondary special   
152  Commercial associate               Higher education   
161  Commercial associate               Higher education   
255  Commercial associate  Secondary / secondary special   

       NAME_FAMILY_STATUS  DAYS_BIRTH  DAYS_EMPLOYED  \
71                Married    -15406.0         -892.0   
124             Separated    -16282.0        -4375.0   
152               Married    -11375.0        -2311.0   
161               Married    -13972.0        -4472.0   
255  Single / not married    -11356.0         -602.0   

     REGION_RATING_CLIENT_W_CITY  EXT_SOURCE_2  FLAG_DOCUMENT_2  \
71                           2.0      0.707126              0.0   
124                          2.0      0.746486              0.0   
152                          2.0      0.616156              0.0   
161                          2.0      0.585859              0.0   
255                          1.0      0.302394              0.0   

     FLAG_DOCUMENT_21  
71                0.0  
124               0.0  
152               0.0  
161               0.0  
255               0.0

In [17]:
cat_var = ['NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 
                     'NAME_INCOME_TYPE','NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS']

In [18]:
final_model_data = pd.get_dummies(model_data, columns=cat_var, drop_first=True)

In [19]:
final_model_data.head()

TARGET  CNT_CHILDREN  AMT_INCOME_TOTAL  AMT_CREDIT  AMT_ANNUITY  \
71      0.0           0.0          103500.0    573628.5      24435.0   
124     0.0           1.0          202500.0    260725.5      16789.5   
152     0.0           0.0          202500.0    675000.0      53329.5   
161     0.0           0.0          162000.0    263686.5      24781.5   
255     1.0           1.0          225000.0   1019205.0      31032.0   

     AMT_GOODS_PRICE  DAYS_BIRTH  DAYS_EMPLOYED  REGION_RATING_CLIENT_W_CITY  \
71          463500.0    -15406.0         -892.0                          2.0   
124         198000.0    -16282.0        -4375.0                          2.0   
152         675000.0    -11375.0        -2311.0                          2.0   
161         238500.0    -13972.0        -4472.0                          2.0   
255         774000.0    -11356.0         -602.0                          1.0   

     EXT_SOURCE_2  FLAG_DOCUMENT_2  FLAG_DOCUMENT_21  \
71       0.707126              0.0               0.0   
124      0.746486              0.0               0.0   
152      0.616156              0.0               0.0   
161      0.585859              0.0               0.0   
255      0.302394              0.0               0.0   

     NAME_CONTRACT_TYPE_Revolving loans  CODE_GENDER_M  FLAG_OWN_REALTY_Y  \
71                                    0              1                  1   
124                                   0              0                  1   
152                                   0              0                  0   
161                                   0              1                  0   
255                                   0              1                  0   

     NAME_INCOME_TYPE_State servant  NAME_INCOME_TYPE_Working  \
71                                0                         1   
124                               0                         1   
152                               0                         0   
161                               0                         0   
255                               0                         0   

     NAME_EDUCATION_TYPE_Higher education  \
71                                      0   
124                                     0   
152                                     1   
161                                     1   
255                                     0   

     NAME_EDUCATION_TYPE_Incomplete higher  \
71                                       0   
124                                      0   
152                                      0   
161                                      0   
255                                      0   

     NAME_EDUCATION_TYPE_Lower secondary  \
71                                     0   
124                                    0   
152                                    0   
161                                    0   
255                                    0   

     NAME_EDUCATION_TYPE_Secondary / secondary special  \
71                                                   1   
124                                                  1   
152                                                  0   
161                                                  0   
255                                                  1   

     NAME_FAMILY_STATUS_Married  NAME_FAMILY_STATUS_Separated  \
71                            1                             0   
124                           0                             1   
152                           1                             0   
161                           1                             0   
255                           0                             0   

     NAME_FAMILY_STATUS_Single / not married  NAME_FAMILY_STATUS_Widow  
71                                         0                         0  
124                                        0                         0  
152                                        0                         0  
161                                        0           

In [20]:
final_model_data.shape

(8602, 25)

In [21]:
# splitting the data
from sklearn.model_selection import train_test_split

X = final_model_data.drop('TARGET', axis =1)
y = final_model_data['TARGET']

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify = y, random_state = 50)

In [23]:
# importing Regression models and evaluation matrices
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [59]:
# Logisticregression Model
logreg = LogisticRegression(class_weight='balanced', random_state=50)
logreg.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', random_state=50)

In [60]:
y_pred_log = logreg.predict(X_test)

In [61]:
print(classification_report(y_test, y_pred_log))

              precision    recall  f1-score   support

         0.0       0.95      0.56      0.70      2423
         1.0       0.07      0.54      0.13       158

    accuracy                           0.56      2581
   macro avg       0.51      0.55      0.42      2581
weighted avg       0.90      0.56      0.67      2581



In [62]:
accuracy_score(y_test, y_pred_log)

0.5590856257264626

In [63]:
print(confusion_matrix(y_test, y_pred_log))

[[1358 1065]
 [  73   85]]


In [49]:
# KNN model
knn = KNeighborsClassifier(n_neighbors=5, metric='euclidean', weights='distance')
knn.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean', weights='distance')

In [50]:
y_pred_knn = knn.predict(X_test)

In [51]:
print(classification_report(y_test, y_pred_knn))

              precision    recall  f1-score   support

         0.0       0.94      0.99      0.96      2423
         1.0       0.03      0.01      0.01       158

    accuracy                           0.93      2581
   macro avg       0.48      0.50      0.49      2581
weighted avg       0.88      0.93      0.90      2581



In [52]:
print(confusion_matrix(y_test, y_pred_knn))

[[2387   36]
 [ 157    1]]


In [64]:
# Random forest model
# Create the model with 500 trees
R_forest = RandomForestClassifier(n_estimators=500, 
                               random_state=50, 
                               max_features = 'sqrt',  
                               n_jobs=-1, verbose = 1)

In [65]:
R_forest.fit(X_train, y_train)

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 184 tasks      | elapsed:    0.4s
[Parallel(n_jobs=-1)]: Done 434 tasks      | elapsed:    0.9s
[Parallel(n_jobs=-1)]: Done 500 out of 500 | elapsed:    1.0s finished


RandomForestClassifier(max_features='sqrt', n_estimators=500, n_jobs=-1,
                       random_state=50, verbose=1)

In [66]:
n_nodes = []
max_depths = []

# Stats about the trees in random forest
for ind_tree in R_forest.estimators_:
    n_nodes.append(ind_tree.tree_.node_count)
    max_depths.append(ind_tree.tree_.max_depth)
    
print(f'Average number of nodes {int(np.mean(n_nodes))}')
print(f'Average maximum depth {int(np.mean(max_depths))}')

Average number of nodes 1030
Average maximum depth 24


In [74]:
# Testing predictions (to determine performance)
y_pred_forest = R_forest.predict(X_test)
y_probs_forest = R_forest.predict_proba(X_test)[:, 1]

[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.1s
[Parallel(n_jobs=8)]: Done 434 tasks      | elapsed:    0.1s
[Parallel(n_jobs=8)]: Done 500 out of 500 | elapsed:    0.1s finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 184 tasks      | elapsed:    0.0s
[Parallel(n_jobs=8)]: Done 434 tasks      | elapsed:    0.1s
[Parallel(n_jobs=8)]: Done 500 out of 500 | elapsed:    0.1s finished


In [76]:
print(y_pred_forest)
print(y_probs_forest.mean())

[0. 0. 0. ... 0. 0. 0.]
0.06850058117008911


In [77]:
accuracy_score(y_test, y_pred_forest)

0.9387834172801239

In [78]:
print(classification_report(y_test, y_pred_forest))

              precision    recall  f1-score   support

         0.0       0.94      1.00      0.97      2423
         1.0       0.00      0.00      0.00       158

    accuracy                           0.94      2581
   macro avg       0.47      0.50      0.48      2581
weighted avg       0.88      0.94      0.91      2581



In [79]:
print(confusion_matrix(y_test, y_pred_forest))

[[2423    0]
 [ 158    0]]
